# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mike Godfrey
email: mike@crudbetter.com
description: > # this means to ignore newlines until "baseurl:"
  Full stack software developer with a keen interest in data management and visualization for smart city solution providers.
  Currently using JavaScript and Elixir to get the job done.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://crudbetter.com" # the base hostname & protocol for your site
twitter_username: crudbetter
github_username:  crudbetter

# Build settings
markdown: kramdown
